<?php
/**
 * Worker Manager - Auto-configuration and management
 *
 * @package PerfAuditPro
 * @namespace PerfAuditPro\Admin
 */

namespace PerfAuditPro\Admin;

if (!defined('ABSPATH')) {
    exit;
}

class Worker_Manager {

    /**
     * Initialize worker manager
     */
    public static function init() {
        add_action('wp_ajax_perfaudit_start_worker', array(__CLASS__, 'start_worker'));
        add_action('wp_ajax_perfaudit_stop_worker', array(__CLASS__, 'stop_worker'));
        add_action('wp_ajax_perfaudit_check_worker', array(__CLASS__, 'check_worker_status'));
        add_action('admin_init', array(__CLASS__, 'auto_configure'));
    }

    /**
     * Auto-configure worker on plugin activation
     */
    public static function auto_configure() {
        // Generate API token if not exists
        $token = get_option('perfaudit_pro_api_token');
        if (empty($token)) {
            $token = self::generate_api_token();
            update_option('perfaudit_pro_api_token', $token);
        }

        // Create worker config file
        self::create_worker_config($token);
    }

    /**
     * Generate secure API token
     */
    private static function generate_api_token() {
        return bin2hex(random_bytes(32));
    }

    /**
     * Create worker configuration file
     */
    private static function create_worker_config($token) {
        $worker_dir = PERFAUDIT_PRO_PLUGIN_DIR . 'worker';
        $env_file = $worker_dir . '/.env';

        if (!file_exists($worker_dir)) {
            wp_mkdir_p($worker_dir);
        }

        $wordpress_url = home_url();
        $worker_id = 'wp-worker-' . get_current_blog_id();

        $config = "# Auto-generated by PerfAudit Pro\n";
        $config .= "# Do not edit manually - changes will be overwritten\n\n";
        $config .= "WORDPRESS_URL={$wordpress_url}\n";
        $config .= "API_TOKEN={$token}\n";
        $config .= "WORKER_ID={$worker_id}\n";
        $config .= "POLL_INTERVAL=30000\n";
        $config .= "MAX_CONCURRENT=2\n";

        file_put_contents($env_file, $config);
    }

    /**
     * Start worker process
     */
    public static function start_worker() {
        check_ajax_referer('perfaudit_worker', 'nonce');

        if (!current_user_can('manage_options')) {
            wp_send_json_error(array('message' => 'Insufficient permissions'));
            return;
        }

        // Auto-configure if needed
        self::auto_configure();

        // Start PHP worker (no Node.js needed)
        $result = self::start_worker_process();

        if ($result['success']) {
            update_option('perfaudit_worker_status', 'running');
            wp_send_json_success(array(
                'message' => 'PHP Worker started successfully (no Node.js required)',
                'pid' => null
            ));
        } else {
            wp_send_json_error(array('message' => $result['message']));
        }
    }

    /**
     * Stop worker process
     */
    public static function stop_worker() {
        check_ajax_referer('perfaudit_worker', 'nonce');

        if (!current_user_can('manage_options')) {
            wp_send_json_error(array('message' => 'Insufficient permissions'));
            return;
        }

        require_once PERFAUDIT_PRO_PLUGIN_DIR . 'includes/worker/class-php-worker.php';
        \PerfAuditPro\Worker\PHP_Worker::stop();

        update_option('perfaudit_worker_status', 'stopped');
        delete_option('perfaudit_worker_pid');

        wp_send_json_success(array('message' => 'Worker stopped'));
    }

    /**
     * Check worker status
     */
    public static function check_worker_status() {
        check_ajax_referer('perfaudit_worker', 'nonce');

        if (!current_user_can('manage_options')) {
            wp_send_json_error(array('message' => 'Insufficient permissions'));
            return;
        }

        require_once PERFAUDIT_PRO_PLUGIN_DIR . 'includes/worker/class-php-worker.php';
        $is_running = \PerfAuditPro\Worker\PHP_Worker::is_running();
        
        $status = $is_running ? 'running' : 'stopped';

        wp_send_json_success(array(
            'status' => $status,
            'pid' => null,
            'node_available' => true,
            'node_message' => 'PHP Worker (No Node.js required)'
        ));
    }

    /**
     * Check if Node.js is available
     */
    private static function check_node_available() {
        exec('node --version 2>&1', $output, $return_var);
        
        if ($return_var !== 0) {
            return array(
                'available' => false,
                'message' => 'Node.js is not installed. Please install Node.js 14+ to run the worker.'
            );
        }

        $version = implode('', $output);
        preg_match('/v(\d+)/', $version, $matches);
        $major_version = isset($matches[1]) ? (int)$matches[1] : 0;

        if ($major_version < 14) {
            return array(
                'available' => false,
                'message' => "Node.js 14+ required. You have: {$version}"
            );
        }

        return array(
            'available' => true,
            'message' => "Node.js {$version} detected"
        );
    }

    /**
     * Start worker process (PHP-based, no Node.js needed)
     */
    private static function start_worker_process() {
        require_once PERFAUDIT_PRO_PLUGIN_DIR . 'includes/worker/class-php-worker.php';
        
        \PerfAuditPro\Worker\PHP_Worker::start();
        
        return array(
            'success' => true,
            'pid' => null,
            'message' => 'PHP Worker started (runs via WP-Cron)'
        );
    }
}

